apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpHVjJZbWwwWTI5ME9rSnBkR052ZEdGa2JXbHUiCgkJfQoJfQp9Cg==
kind: Secret
metadata:
  creationTimestamp: "2021-09-09T06:52:17Z"
  name: registrycred
  namespace: default
  resourceVersion: "265394"
  uid: e0a17a53-7d4e-48ad-9354-2f12e4804d26
type: kubernetes.io/dockerconfigjson
