apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script
data: 
  mysql.sh: |-
    #!/bin/bash
    mysql -uroot -pgroot << EOF
    use know2;
    UPDATE wp_options SET option_value="http://192.168.49.2:31004/" WHERE option_name = "home";
    UPDATE wp_options SET option_value="http://192.168.49.2:31004/" WHERE option_name = "siteurl";
    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'groot';
    FLUSH PRIVILEGES;
    EOF