apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: wordpress-know2
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: wordpress-know2
  clusterIP: None
