apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
  labels:
    app: wordpress-know2
spec:
  ports:
  - port: 80
    nodePort: 31004
    protocol: TCP
  selector:
    name: wp-host
  type: NodePort
